// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAggregateMetrics() {
  return window['go']['main']['App']['GetAggregateMetrics']();
}

export function GetDockerInfo() {
  return window['go']['main']['App']['GetDockerInfo']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListContainers() {
  return window['go']['main']['App']['ListContainers']();
}

export function ListImages() {
  return window['go']['main']['App']['ListImages']();
}

export function PullImages(arg1) {
  return window['go']['main']['App']['PullImages'](arg1);
}

export function RemoveContainer(arg1) {
  return window['go']['main']['App']['RemoveContainer'](arg1);
}

export function RemoveImage(arg1) {
  return window['go']['main']['App']['RemoveImage'](arg1);
}

export function RunImage(arg1) {
  return window['go']['main']['App']['RunImage'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopContainerLogs() {
  return window['go']['main']['App']['StopContainerLogs']();
}

export function StopContainerStats() {
  return window['go']['main']['App']['StopContainerStats']();
}

export function StreamContainerLogs(arg1) {
  return window['go']['main']['App']['StreamContainerLogs'](arg1);
}

export function StreamContainerResponse(arg1) {
  return window['go']['main']['App']['StreamContainerResponse'](arg1);
}
