// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {client} from '../models';

export function GetDockerInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListContainers():Promise<Array<main.ContainerItem>>;

export function StartContainer(arg1:string):Promise<client.ContainerStartResult>;

export function StopContainer(arg1:string):Promise<client.ContainerStopResult>;

export function StopContainerLogs():Promise<void>;

export function StreamContainerLogs(arg1:string):Promise<void>;
