// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {client} from '../models';

export function CancelPullImage():Promise<void>;

export function GetAggregateMetrics():Promise<main.AggregateMetrics>;

export function GetDockerInfo():Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfoData>;

export function Greet(arg1:string):Promise<string>;

export function ListContainers():Promise<Array<main.ContainerItem>>;

export function ListImages():Promise<Array<main.ImageItem>>;

export function PullImages(arg1:string):Promise<void>;

export function RemoveContainer(arg1:string):Promise<client.ContainerRemoveResult>;

export function RemoveImage(arg1:string):Promise<client.ImageRemoveResult>;

export function RunImage(arg1:main.RunImageOptions):Promise<void>;

export function StartContainer(arg1:string):Promise<client.ContainerStartResult>;

export function StopContainer(arg1:string):Promise<client.ContainerStopResult>;

export function StopContainerLogs():Promise<void>;

export function StopContainerStats():Promise<void>;

export function StreamContainerLogs(arg1:string):Promise<void>;

export function StreamContainerResponse(arg1:string):Promise<void>;
